<?php

namespace Database\Seeders;

use App\Models\Thana;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ThanaSeeder extends Seeder
{
    public function run(): void
    {
        Thana::insert([
            ["id" => 1, "district_id"  =>  "1", "thana_name"  =>  "BAGERHAT"],
            ["id" => 2, "district_id"  =>  "1", "thana_name"  =>  "BAGERHAT SADAR"],
            ["id" => 3, "district_id"  =>  "1", "thana_name"  =>  "CHITALMARI"],
            ["id" => 4, "district_id"  =>  "1", "thana_name"  =>  "FAKIRHAT"],
            ["id" => 5, "district_id"  =>  "1", "thana_name"  =>  "KACHUA"],
            ["id" => 6, "district_id"  =>  "1", "thana_name"  =>  "MOLLAHAT"],
            ["id" => 7, "district_id"  =>  "1", "thana_name"  =>  "MONGLA"],
            ["id" => 8, "district_id"  =>  "1", "thana_name"  =>  "MORRELGANJ"],
            ["id" => 9, "district_id"  =>  "1", "thana_name"  =>  "RAMPAL"],
            ["id" => 10, "district_id"  =>  "1", "thana_name"  =>  "SARANKHOLA"],
            ["id" => 11, "district_id"  =>  "2", "thana_name"  =>  "BANDARBAN"],
            ["id" => 12, "district_id"  =>  "2", "thana_name"  =>  "ALIKADAM"],
            ["id" => 13, "district_id"  =>  "2", "thana_name"  =>  "BANDARBAN SADAR"],
            ["id" => 14, "district_id"  =>  "2", "thana_name"  =>  "LAMA"],
            ["id" => 15, "district_id"  =>  "2", "thana_name"  =>  "NAIKHONGCHHARI"],
            ["id" => 16, "district_id"  =>  "2", "thana_name"  =>  "ROWANGCHARI"],
            ["id" => 17, "district_id"  =>  "2", "thana_name"  =>  "RUMA"],
            ["id" => 18, "district_id"  =>  "2", "thana_name"  =>  "THANCHI"],
            ["id" => 19, "district_id"  =>  "3", "thana_name"  =>  "BARGUNA"],
            ["id" => 20, "district_id"  =>  "3", "thana_name"  =>  "AMTOLI"],
            ["id" => 21, "district_id"  =>  "3", "thana_name"  =>  "BAMNA"],
            ["id" => 22, "district_id"  =>  "3", "thana_name"  =>  "BARGUNA"],
            ["id" => 23, "district_id"  =>  "3", "thana_name"  =>  "BETAGI"],
            ["id" => 24, "district_id"  =>  "3", "thana_name"  =>  "PATHARGHATA"],
            ["id" => 25, "district_id"  =>  "3", "thana_name"  =>  "TALTOLI"],
            ["id" => 26, "district_id"  =>  "4", "thana_name"  =>  "BARISHAL"],
            ["id" => 27, "district_id"  =>  "4", "thana_name"  =>  "AGAILJHARA"],
            ["id" => 28, "district_id"  =>  "4", "thana_name"  =>  "AIRPORT"],
            ["id" => 29, "district_id"  =>  "4", "thana_name"  =>  "BABUGANJ"],
            ["id" => 30, "district_id"  =>  "4", "thana_name"  =>  "BAKERGANJ"],
            ["id" => 31, "district_id"  =>  "4", "thana_name"  =>  "BANARIPARA"],
            ["id" => 32, "district_id"  =>  "4", "thana_name"  =>  "BANDAR"],
            ["id" => 33, "district_id"  =>  "4", "thana_name"  =>  "GOURNADI"],
            ["id" => 34, "district_id"  =>  "4", "thana_name"  =>  "HIZLA"],
            ["id" => 35, "district_id"  =>  "4", "thana_name"  =>  "KAWNIA"],
            ["id" => 36, "district_id"  =>  "4", "thana_name"  =>  "KAZIRHAT"],
            ["id" => 37, "district_id"  =>  "4", "thana_name"  =>  "KOTWALI MODEL"],
            ["id" => 38, "district_id"  =>  "4", "thana_name"  =>  "MEHENDIGANJ"],
            ["id" => 39, "district_id"  =>  "4", "thana_name"  =>  "MULADI"],
            ["id" => 40, "district_id"  =>  "4", "thana_name"  =>  "WAZIRPUR"],
            ["id" => 41, "district_id"  =>  "5", "thana_name"  =>  "BHOLA"],
            ["id" => 42, "district_id"  =>  "5", "thana_name"  =>  "BHOLA SADAR"],
            ["id" => 43, "district_id"  =>  "5", "thana_name"  =>  "BURHANUDDIN"],
            ["id" => 44, "district_id"  =>  "5", "thana_name"  =>  "CHARFASSON"],
            ["id" => 45, "district_id"  =>  "5", "thana_name"  =>  "DAKSHIN AICHA"],
            ["id" => 46, "district_id"  =>  "5", "thana_name"  =>  "DAULATKHAN"],
            ["id" => 47, "district_id"  =>  "5", "thana_name"  =>  "DULARHAT"],
            ["id" => 48, "district_id"  =>  "5", "thana_name"  =>  "LALMOHAN"],
            ["id" => 49, "district_id"  =>  "5", "thana_name"  =>  "MANPURA"],
            ["id" => 50, "district_id"  =>  "5", "thana_name"  =>  "SOSHIVUSION"],
            ["id" => 51, "district_id"  =>  "5", "thana_name"  =>  "TAZUMUDDIN"],
            ["id" => 52, "district_id"  =>  "6", "thana_name"  =>  "BOGURA"],
            ["id" => 53, "district_id"  =>  "6", "thana_name"  =>  "ADAMDIGHI"],
            ["id" => 54, "district_id"  =>  "6", "thana_name"  =>  "BOGURA SADAR"],
            ["id" => 55, "district_id"  =>  "6", "thana_name"  =>  "DHUNAT"],
            ["id" => 56, "district_id"  =>  "6", "thana_name"  =>  "DHUPCHANCHIA"],
            ["id" => 57, "district_id"  =>  "6", "thana_name"  =>  "GABTALI"],
            ["id" => 58, "district_id"  =>  "6", "thana_name"  =>  "KAHALOO"],
            ["id" => 59, "district_id"  =>  "6", "thana_name"  =>  "NANDIGRAM"],
            ["id" => 60, "district_id"  =>  "6", "thana_name"  =>  "SARIAKANDI"],
            ["id" => 61, "district_id"  =>  "6", "thana_name"  =>  "SHAJAHANPUR"],
            ["id" => 62, "district_id"  =>  "6", "thana_name"  =>  "SHERPUR"],
            ["id" => 63, "district_id"  =>  "6", "thana_name"  =>  "SHIBGANJ"],
            ["id" => 64, "district_id"  =>  "6", "thana_name"  =>  "SONATOLA"],
            ["id" => 65, "district_id"  =>  "7", "thana_name"  =>  "BRAHMANBARIA"],
            ["id" => 66, "district_id"  =>  "7", "thana_name"  =>  "AKHAURA"],
            ["id" => 67, "district_id"  =>  "7", "thana_name"  =>  "ASHUGANJ"],
            ["id" => 68, "district_id"  =>  "7", "thana_name"  =>  "BANCHARAMPUR"],
            ["id" => 69, "district_id"  =>  "7", "thana_name"  =>  "BIJOYNAGAR"],
            ["id" => 70, "district_id"  =>  "7", "thana_name"  =>  "BRAHMANBARIA SADAR"],
            ["id" => 71, "district_id"  =>  "7", "thana_name"  =>  "KASBA"],
            ["id" => 72, "district_id"  =>  "7", "thana_name"  =>  "NABINAGAR"],
            ["id" => 73, "district_id"  =>  "7", "thana_name"  =>  "NASIRNAGAR"],
            ["id" => 74, "district_id"  =>  "7", "thana_name"  =>  "SARAIL"],
            ["id" => 75, "district_id"  =>  "8", "thana_name"  =>  "CHANDPUR"],
            ["id" => 76, "district_id"  =>  "8", "thana_name"  =>  "CHANDPUR SADAR"],
            ["id" => 77, "district_id"  =>  "8", "thana_name"  =>  "FARIDGANJ"],
            ["id" => 78, "district_id"  =>  "8", "thana_name"  =>  "HAIMCHAR"],
            ["id" => 79, "district_id"  =>  "8", "thana_name"  =>  "HAZIGANJ"],
            ["id" => 80, "district_id"  =>  "8", "thana_name"  =>  "KACHUA"],
            ["id" => 81, "district_id"  =>  "8", "thana_name"  =>  "MATLAB DAKSHIN"],
            ["id" => 82, "district_id"  =>  "8", "thana_name"  =>  "MATLAB UTTAR"],
            ["id" => 83, "district_id"  =>  "8", "thana_name"  =>  "SHAHRASTI"],
            ["id" => 84, "district_id"  =>  "9", "thana_name"  =>  "CHAPAINAWABGANJ"],
            ["id" => 85, "district_id"  =>  "9", "thana_name"  =>  "BHOLAHAT"],
            ["id" => 86, "district_id"  =>  "9", "thana_name"  =>  "GOMOSTAPUR"],
            ["id" => 87, "district_id"  =>  "9", "thana_name"  =>  "NACHOL"],
            ["id" => 88, "district_id"  =>  "9", "thana_name"  =>  "CHAPAINAWABGANJ SADAR"],
            ["id" => 89, "district_id"  =>  "9", "thana_name"  =>  "SHIBGANJ"],
            ["id" => 90, "district_id"  =>  "10", "thana_name"  =>  "CHATTOGRAM"],
            ["id" => 91, "district_id"  =>  "10", "thana_name"  =>  "AKBARSHAH"],
            ["id" => 92, "district_id"  =>  "10", "thana_name"  =>  "ANWARA"],
            ["id" => 93, "district_id"  =>  "10", "thana_name"  =>  "BAKALIA"],
            ["id" => 94, "district_id"  =>  "10", "thana_name"  =>  "BANDAR"],
            ["id" => 95, "district_id"  =>  "10", "thana_name"  =>  "BANSHKHALI"],
            ["id" => 96, "district_id"  =>  "10", "thana_name"  =>  "BAYEZID BOSTAMI"],
            ["id" => 97, "district_id"  =>  "10", "thana_name"  =>  "BHUJPUR"],
            ["id" => 98, "district_id"  =>  "10", "thana_name"  =>  "BOALKHALI"],
            ["id" => 99, "district_id"  =>  "10", "thana_name"  =>  "CHANDANAISH"],
            ["id" => 100, "district_id"  =>  "10", "thana_name"  =>  "CHANDGAON"],
            ["id" => 101, "district_id"  =>  "10", "thana_name"  =>  "CHAWKBAZAR"],
            ["id" => 102, "district_id"  =>  "10", "thana_name"  =>  "DOUBLE MOORING"],
            ["id" => 103, "district_id"  =>  "10", "thana_name"  =>  "EPZ"],
            ["id" => 104, "district_id"  =>  "10", "thana_name"  =>  "FATIKCHHARI"],
            ["id" => 105, "district_id"  =>  "10", "thana_name"  =>  "HALISHAHAR"],
            ["id" => 106, "district_id"  =>  "10", "thana_name"  =>  "HATHAZARI"],
            ["id" => 107, "district_id"  =>  "10", "thana_name"  =>  "JORARGANJ"],
            ["id" => 108, "district_id"  =>  "10", "thana_name"  =>  "KARNAPHULI"],
            ["id" => 109, "district_id"  =>  "10", "thana_name"  =>  "KHULSHI"],
            ["id" => 110, "district_id"  =>  "10", "thana_name"  =>  "KOTOWALI"],
            ["id" => 111, "district_id"  =>  "10", "thana_name"  =>  "LOHAGARA"],
            ["id" => 112, "district_id"  =>  "10", "thana_name"  =>  "MIRSHARAI"],
            ["id" => 113, "district_id"  =>  "10", "thana_name"  =>  "PAHARTOLI"],
            ["id" => 114, "district_id"  =>  "10", "thana_name"  =>  "PANCHLAISH"],
            ["id" => 115, "district_id"  =>  "10", "thana_name"  =>  "PATENGA"],
            ["id" => 116, "district_id"  =>  "10", "thana_name"  =>  "PATIYA"],
            ["id" => 117, "district_id"  =>  "10", "thana_name"  =>  "RANGUNIA"],
            ["id" => 118, "district_id"  =>  "10", "thana_name"  =>  "RAOZAN"],
            ["id" => 119, "district_id"  =>  "10", "thana_name"  =>  "SADARGHAT"],
            ["id" => 120, "district_id"  =>  "10", "thana_name"  =>  "SANDWIP"],
            ["id" => 121, "district_id"  =>  "10", "thana_name"  =>  "SATKANIA"],
            ["id" => 122, "district_id"  =>  "10", "thana_name"  =>  "SITAKUNDA"],
            ["id" => 123, "district_id"  =>  "11", "thana_name"  =>  "CHUADANGA"],
            ["id" => 124, "district_id"  =>  "11", "thana_name"  =>  "ALAMDANGA"],
            ["id" => 125, "district_id"  =>  "11", "thana_name"  =>  "CHUADANGA SADAR"],
            ["id" => 126, "district_id"  =>  "11", "thana_name"  =>  "DAMURHUDA"],
            ["id" => 127, "district_id"  =>  "11", "thana_name"  =>  "DARSHANA"],
            ["id" => 128, "district_id"  =>  "11", "thana_name"  =>  "JIBANNAGAR"],
            ["id" => 129, "district_id"  =>  "12", "thana_name"  =>  "COX'S BAZAR"],
            ["id" => 130, "district_id"  =>  "12", "thana_name"  =>  "CHAKARIA"],
            ["id" => 131, "district_id"  =>  "12", "thana_name"  =>  "COX'S BAZAR"],
            ["id" => 132, "district_id"  =>  "12", "thana_name"  =>  "EIDGAON"],
            ["id" => 133, "district_id"  =>  "12", "thana_name"  =>  "KUTUBDIA"],
            ["id" => 134, "district_id"  =>  "12", "thana_name"  =>  "MAHESHKHALI"],
            ["id" => 135, "district_id"  =>  "12", "thana_name"  =>  "PEKUA"],
            ["id" => 136, "district_id"  =>  "12", "thana_name"  =>  "RAMU"],
            ["id" => 137, "district_id"  =>  "12", "thana_name"  =>  "TEKNAF"],
            ["id" => 138, "district_id"  =>  "12", "thana_name"  =>  "UKHIA"],
            ["id" => 139, "district_id"  =>  "13", "thana_name"  =>  "CUMILLA"],
            ["id" => 140, "district_id"  =>  "13", "thana_name"  =>  "BANGORA BAZAR"],
            ["id" => 141, "district_id"  =>  "13", "thana_name"  =>  "BARURA"],
            ["id" => 142, "district_id"  =>  "13", "thana_name"  =>  "BRAHMANPARA"],
            ["id" => 143, "district_id"  =>  "13", "thana_name"  =>  "BURICHONG"],
            ["id" => 144, "district_id"  =>  "13", "thana_name"  =>  "CHANDINA"],
            ["id" => 145, "district_id"  =>  "13", "thana_name"  =>  "CHAUDDAGRAM"],
            ["id" => 146, "district_id"  =>  "13", "thana_name"  =>  "DAUDKANDI"],
            ["id" => 147, "district_id"  =>  "13", "thana_name"  =>  "DEBIDWAR"],
            ["id" => 148, "district_id"  =>  "13", "thana_name"  =>  "HOMNA"],
            ["id" => 149, "district_id"  =>  "13", "thana_name"  =>  "KOTWALI MODEL"],
            ["id" => 150, "district_id"  =>  "13", "thana_name"  =>  "LAKSAM"],
            ["id" => 151, "district_id"  =>  "13", "thana_name"  =>  "LALMAI"],
            ["id" => 152, "district_id"  =>  "13", "thana_name"  =>  "MANOHARGANJ"],
            ["id" => 153, "district_id"  =>  "13", "thana_name"  =>  "MEGHNA"],
            ["id" => 154, "district_id"  =>  "13", "thana_name"  =>  "MURADNAGAR"],
            ["id" => 155, "district_id"  =>  "13", "thana_name"  =>  "NANGALKOT"],
            ["id" => 156, "district_id"  =>  "13", "thana_name"  =>  "SADAR DAKSHIN"],
            ["id" => 157, "district_id"  =>  "13", "thana_name"  =>  "TITAS"],
            ["id" => 158, "district_id"  =>  "14", "thana_name"  =>  "DHAKA"],
            ["id" => 159, "district_id"  =>  "14", "thana_name"  =>  "ADABOR"],
            ["id" => 160, "district_id"  =>  "14", "thana_name"  =>  "AIRPORT"],
            ["id" => 161, "district_id"  =>  "14", "thana_name"  =>  "ASHULIA"],
            ["id" => 162, "district_id"  =>  "14", "thana_name"  =>  "BADDA"],
            ["id" => 163, "district_id"  =>  "14", "thana_name"  =>  "BANANI"],
            ["id" => 164, "district_id"  =>  "14", "thana_name"  =>  "BANGSHAL"],
            ["id" => 165, "district_id"  =>  "14", "thana_name"  =>  "CANTONMENT"],
            ["id" => 166, "district_id"  =>  "14", "thana_name"  =>  "CHAWKBAZAR"],
            ["id" => 167, "district_id"  =>  "14", "thana_name"  =>  "DAKSHINKHAN"],
            ["id" => 168, "district_id"  =>  "14", "thana_name"  =>  "DARUS SALAM"],
            ["id" => 169, "district_id"  =>  "14", "thana_name"  =>  "DEMRA"],
            ["id" => 170, "district_id"  =>  "14", "thana_name"  =>  "DHAMRAI"],
            ["id" => 171, "district_id"  =>  "14", "thana_name"  =>  "DHANMONDI"],
            ["id" => 172, "district_id"  =>  "14", "thana_name"  =>  "DOHAR"],
            ["id" => 173, "district_id"  =>  "14", "thana_name"  =>  "GENDARIA"],
            ["id" => 174, "district_id"  =>  "14", "thana_name"  =>  "GULSHAN"],
            ["id" => 175, "district_id"  =>  "14", "thana_name"  =>  "HATIRJHEEL"],
            ["id" => 176, "district_id"  =>  "14", "thana_name"  =>  "HAZARIBAGH"],
            ["id" => 177, "district_id"  =>  "14", "thana_name"  =>  "JATRABARI"],
            ["id" => 178, "district_id"  =>  "14", "thana_name"  =>  "KADOMTOLI"],
            ["id" => 179, "district_id"  =>  "14", "thana_name"  =>  "KAFRUL"],
            ["id" => 180, "district_id"  =>  "14", "thana_name"  =>  "KALABAGAN"],
            ["id" => 181, "district_id"  =>  "14", "thana_name"  =>  "KAMRANGIRCHAR"],
            ["id" => 182, "district_id"  =>  "14", "thana_name"  =>  "KERANIGANJ"],
            ["id" => 183, "district_id"  =>  "14", "thana_name"  =>  "KHILGAON"],
            ["id" => 184, "district_id"  =>  "14", "thana_name"  =>  "KHILKHET"],
            ["id" => 185, "district_id"  =>  "14", "thana_name"  =>  "KOTWALI"],
            ["id" => 186, "district_id"  =>  "14", "thana_name"  =>  "LALBAGH"],
            ["id" => 187, "district_id"  =>  "14", "thana_name"  =>  "MIRPUR"],
            ["id" => 188, "district_id"  =>  "14", "thana_name"  =>  "MOHAMMADPUR"],
            ["id" => 189, "district_id"  =>  "14", "thana_name"  =>  "MOTIJHEEL"],
            ["id" => 190, "district_id"  =>  "14", "thana_name"  =>  "MUGDA"],
            ["id" => 191, "district_id"  =>  "14", "thana_name"  =>  "NAWABGONJ"],
            ["id" => 192, "district_id"  =>  "14", "thana_name"  =>  "NEW MARKET"],
            ["id" => 193, "district_id"  =>  "14", "thana_name"  =>  "PALLABI"],
            ["id" => 194, "district_id"  =>  "14", "thana_name"  =>  "PALTAN"],
            ["id" => 195, "district_id"  =>  "14", "thana_name"  =>  "RAMNA"],
            ["id" => 196, "district_id"  =>  "14", "thana_name"  =>  "RAMPURA"],
            ["id" => 197, "district_id"  =>  "14", "thana_name"  =>  "RUPNAGAR"],
            ["id" => 198, "district_id"  =>  "14", "thana_name"  =>  "SABUJBAGH"],
            ["id" => 199, "district_id"  =>  "14", "thana_name"  =>  "SAVAR"],
            ["id" => 200, "district_id"  =>  "14", "thana_name"  =>  "SHAH ALI"],
            ["id" => 201, "district_id"  =>  "14", "thana_name"  =>  "SHAHBAGH"],
            ["id" => 202, "district_id"  =>  "14", "thana_name"  =>  "SHAHJAHANPUR"],
            ["id" => 203, "district_id"  =>  "14", "thana_name"  =>  "SHAMPUR"],
            ["id" => 204, "district_id"  =>  "14", "thana_name"  =>  "SHER-E-BANGLA NAGAR"],
            ["id" => 205, "district_id"  =>  "14", "thana_name"  =>  "SOUTH KERANIGANJ"],
            ["id" => 206, "district_id"  =>  "14", "thana_name"  =>  "SUTRAPUR"],
            ["id" => 207, "district_id"  =>  "14", "thana_name"  =>  "TEJGAON"],
            ["id" => 208, "district_id"  =>  "14", "thana_name"  =>  "TEJGAON INDUSTRIAL AREA"],
            ["id" => 209, "district_id"  =>  "14", "thana_name"  =>  "TURAG"],
            ["id" => 210, "district_id"  =>  "14", "thana_name"  =>  "UTTARA EAST"],
            ["id" => 211, "district_id"  =>  "14", "thana_name"  =>  "UTTARA WEST"],
            ["id" => 212, "district_id"  =>  "14", "thana_name"  =>  "UTTARKHAN"],
            ["id" => 213, "district_id"  =>  "14", "thana_name"  =>  "VASHANTEK"],
            ["id" => 214, "district_id"  =>  "14", "thana_name"  =>  "VATARA"],
            ["id" => 215, "district_id"  =>  "14", "thana_name"  =>  "WARI"],
            ["id" => 216, "district_id"  =>  "15", "thana_name"  =>  "DINAJPUR"],
            ["id" => 217, "district_id"  =>  "15", "thana_name"  =>  "BIRAL"],
            ["id" => 218, "district_id"  =>  "15", "thana_name"  =>  "BIRAMPUR"],
            ["id" => 219, "district_id"  =>  "15", "thana_name"  =>  "BIRGANJ"],
            ["id" => 220, "district_id"  =>  "15", "thana_name"  =>  "BOCHAGANJ"],
            ["id" => 221, "district_id"  =>  "15", "thana_name"  =>  "CHIRIRBANDAR"],
            ["id" => 222, "district_id"  =>  "15", "thana_name"  =>  "GHORAGHAT"],
            ["id" => 223, "district_id"  =>  "15", "thana_name"  =>  "HAKIMPUR"],
            ["id" => 224, "district_id"  =>  "15", "thana_name"  =>  "KAHAROLE"],
            ["id" => 225, "district_id"  =>  "15", "thana_name"  =>  "KHANSAMA"],
            ["id" => 226, "district_id"  =>  "15", "thana_name"  =>  "KOTWALI"],
            ["id" => 227, "district_id"  =>  "15", "thana_name"  =>  "NAWABGANJ"],
            ["id" => 228, "district_id"  =>  "15", "thana_name"  =>  "PARBATIPUR"],
            ["id" => 229, "district_id"  =>  "15", "thana_name"  =>  "PHULBARI"],
            ["id" => 230, "district_id"  =>  "16", "thana_name"  =>  "FARIDPUR"],
            ["id" => 231, "district_id"  =>  "16", "thana_name"  =>  "ALFADANGA"],
            ["id" => 232, "district_id"  =>  "16", "thana_name"  =>  "BHANGA"],
            ["id" => 233, "district_id"  =>  "16", "thana_name"  =>  "BOALMARI"],
            ["id" => 234, "district_id"  =>  "16", "thana_name"  =>  "CHAR BHADRASAN"],
            ["id" => 235, "district_id"  =>  "16", "thana_name"  =>  "KOTWALI"],
            ["id" => 236, "district_id"  =>  "16", "thana_name"  =>  "MADHUKHALI"],
            ["id" => 237, "district_id"  =>  "16", "thana_name"  =>  "NAGARKANDA"],
            ["id" => 238, "district_id"  =>  "16", "thana_name"  =>  "SADARPUR"],
            ["id" => 239, "district_id"  =>  "16", "thana_name"  =>  "SALTHA"],
            ["id" => 240, "district_id"  =>  "17", "thana_name"  =>  "FENI"],
            ["id" => 241, "district_id"  =>  "17", "thana_name"  =>  "CHHAGALNAIYA"],
            ["id" => 242, "district_id"  =>  "17", "thana_name"  =>  "DAGONBHUIYAN"],
            ["id" => 243, "district_id"  =>  "17", "thana_name"  =>  "FENI SADAR"],
            ["id" => 244, "district_id"  =>  "17", "thana_name"  =>  "FULGAZI"],
            ["id" => 245, "district_id"  =>  "17", "thana_name"  =>  "PARSHURAM"],
            ["id" => 246, "district_id"  =>  "17", "thana_name"  =>  "SONAGAZI"],
            ["id" => 247, "district_id"  =>  "18", "thana_name"  =>  "GAIBANDHA"],
            ["id" => 248, "district_id"  =>  "18", "thana_name"  =>  "FULCHHARI"],
            ["id" => 249, "district_id"  =>  "18", "thana_name"  =>  "GAIBANDHA SADAR"],
            ["id" => 250, "district_id"  =>  "18", "thana_name"  =>  "GOBINDAGANJ"],
            ["id" => 251, "district_id"  =>  "18", "thana_name"  =>  "PALASHBARI"],
            ["id" => 252, "district_id"  =>  "18", "thana_name"  =>  "SADULLAPUR"],
            ["id" => 253, "district_id"  =>  "18", "thana_name"  =>  "SHAGHATA"],
            ["id" => 254, "district_id"  =>  "18", "thana_name"  =>  "SUNDARGANJ"],
            ["id" => 255, "district_id"  =>  "19", "thana_name"  =>  "GAZIPUR"],
            ["id" => 256, "district_id"  =>  "19", "thana_name"  =>  "BASON"],
            ["id" => 257, "district_id"  =>  "19", "thana_name"  =>  "GACHA"],
            ["id" => 258, "district_id"  =>  "19", "thana_name"  =>  "GAZIPUR SADAR"],
            ["id" => 259, "district_id"  =>  "19", "thana_name"  =>  "JOYDEBPUR"],
            ["id" => 260, "district_id"  =>  "19", "thana_name"  =>  "KALIAKAIR"],
            ["id" => 261, "district_id"  =>  "19", "thana_name"  =>  "KALIGANJ"],
            ["id" => 262, "district_id"  =>  "19", "thana_name"  =>  "KAPASIA"],
            ["id" => 263, "district_id"  =>  "19", "thana_name"  =>  "KASIMPUR"],
            ["id" => 264, "district_id"  =>  "19", "thana_name"  =>  "KONABARI"],
            ["id" => 265, "district_id"  =>  "19", "thana_name"  =>  "PUBAIL"],
            ["id" => 266, "district_id"  =>  "19", "thana_name"  =>  "SREEPUR"],
            ["id" => 267, "district_id"  =>  "19", "thana_name"  =>  "TONGI EAST"],
            ["id" => 268, "district_id"  =>  "19", "thana_name"  =>  "TONGI WEST"],
            ["id" => 269, "district_id"  =>  "20", "thana_name"  =>  "GOPALGANJ"],
            ["id" => 270, "district_id"  =>  "20", "thana_name"  =>  "GOPALGANJ"],
            ["id" => 271, "district_id"  =>  "20", "thana_name"  =>  "KASHIANI"],
            ["id" => 272, "district_id"  =>  "20", "thana_name"  =>  "KOTALIPARA"],
            ["id" => 273, "district_id"  =>  "20", "thana_name"  =>  "MUKSUDPUR"],
            ["id" => 274, "district_id"  =>  "20", "thana_name"  =>  "TUNGIPARA"],
            ["id" => 275, "district_id"  =>  "21", "thana_name"  =>  "HABIGANJ"],
            ["id" => 276, "district_id"  =>  "21", "thana_name"  =>  "AJMIRIGANJ"],
            ["id" => 277, "district_id"  =>  "21", "thana_name"  =>  "BAHUBAL"],
            ["id" => 278, "district_id"  =>  "21", "thana_name"  =>  "BANIYACHONG"],
            ["id" => 279, "district_id"  =>  "21", "thana_name"  =>  "CHUNARUGHAT"],
            ["id" => 280, "district_id"  =>  "21", "thana_name"  =>  "HABIGANJ"],
            ["id" => 281, "district_id"  =>  "21", "thana_name"  =>  "LAKHAI"],
            ["id" => 282, "district_id"  =>  "21", "thana_name"  =>  "MADHABPUR"],
            ["id" => 283, "district_id"  =>  "21", "thana_name"  =>  "NABIGANJ"],
            ["id" => 284, "district_id"  =>  "21", "thana_name"  =>  "SHAESTAGONJ"],
            ["id" => 285, "district_id"  =>  "22", "thana_name"  =>  "JAMALPUR"],
            ["id" => 286, "district_id"  =>  "22", "thana_name"  =>  "BAKSHIGONJ"],
            ["id" => 287, "district_id"  =>  "22", "thana_name"  =>  "DEWANGANJ"],
            ["id" => 288, "district_id"  =>  "22", "thana_name"  =>  "ISLAMPUR"],
            ["id" => 289, "district_id"  =>  "22", "thana_name"  =>  "JAMALPUR SADAR"],
            ["id" => 290, "district_id"  =>  "22", "thana_name"  =>  "MADARGANJ"],
            ["id" => 291, "district_id"  =>  "22", "thana_name"  =>  "MELANDOHO"],
            ["id" => 292, "district_id"  =>  "22", "thana_name"  =>  "SARISHABARI"],
            ["id" => 293, "district_id"  =>  "23", "thana_name"  =>  "JASHORE"],
            ["id" => 294, "district_id"  =>  "23", "thana_name"  =>  "ABHAYNAGAR"],
            ["id" => 295, "district_id"  =>  "23", "thana_name"  =>  "BAGHERPARA"],
            ["id" => 296, "district_id"  =>  "23", "thana_name"  =>  "BENAPOLE PORT"],
            ["id" => 297, "district_id"  =>  "23", "thana_name"  =>  "CHAUGACHHA"],
            ["id" => 298, "district_id"  =>  "23", "thana_name"  =>  "JHIKARGACHHA"],
            ["id" => 299, "district_id"  =>  "23", "thana_name"  =>  "KESHABPUR"],
            ["id" => 300, "district_id"  =>  "23", "thana_name"  =>  "KOTWALI"],
            ["id" => 301, "district_id"  =>  "23", "thana_name"  =>  "MANIRAMPUR"],
            ["id" => 302, "district_id"  =>  "23", "thana_name"  =>  "SHARSHA"],
            ["id" => 303, "district_id"  =>  "24", "thana_name"  =>  "JHALAKATI"],
            ["id" => 304, "district_id"  =>  "24", "thana_name"  =>  "JHALOKATI"],
            ["id" => 305, "district_id"  =>  "24", "thana_name"  =>  "KATHALIA"],
            ["id" => 306, "district_id"  =>  "24", "thana_name"  =>  "NALCHITY"],
            ["id" => 307, "district_id"  =>  "24", "thana_name"  =>  "RAJAPUR"],
            ["id" => 308, "district_id"  =>  "25", "thana_name"  =>  "JHENAIDAH"],
            ["id" => 309, "district_id"  =>  "25", "thana_name"  =>  "HARINAKUNDA"],
            ["id" => 310, "district_id"  =>  "25", "thana_name"  =>  "JHENAIDAH"],
            ["id" => 311, "district_id"  =>  "25", "thana_name"  =>  "KALIGANJ"],
            ["id" => 312, "district_id"  =>  "25", "thana_name"  =>  "KOTCHANDPUR"],
            ["id" => 313, "district_id"  =>  "25", "thana_name"  =>  "MAHESHPUR"],
            ["id" => 314, "district_id"  =>  "25", "thana_name"  =>  "SHAILKUPA"],
            ["id" => 315, "district_id"  =>  "26", "thana_name"  =>  "JOYPURHAT"],
            ["id" => 316, "district_id"  =>  "26", "thana_name"  =>  "AKKELPUR"],
            ["id" => 317, "district_id"  =>  "26", "thana_name"  =>  "JOYPURHAT"],
            ["id" => 318, "district_id"  =>  "26", "thana_name"  =>  "KALAI"],
            ["id" => 319, "district_id"  =>  "26", "thana_name"  =>  "KHETLAL"],
            ["id" => 320, "district_id"  =>  "26", "thana_name"  =>  "PANCHBIBI"],
            ["id" => 321, "district_id"  =>  "27", "thana_name"  =>  "KHAGRACHARI"],
            ["id" => 322, "district_id"  =>  "27", "thana_name"  =>  "DIGHINALA"],
            ["id" => 323, "district_id"  =>  "27", "thana_name"  =>  "GUIMARA"],
            ["id" => 324, "district_id"  =>  "27", "thana_name"  =>  "KHAGRACHARI"],
            ["id" => 325, "district_id"  =>  "27", "thana_name"  =>  "LAKSHMICHARI"],
            ["id" => 326, "district_id"  =>  "27", "thana_name"  =>  "MAHALCHARI"],
            ["id" => 327, "district_id"  =>  "27", "thana_name"  =>  "MANIKCHARI"],
            ["id" => 328, "district_id"  =>  "27", "thana_name"  =>  "MATIRANGA"],
            ["id" => 329, "district_id"  =>  "27", "thana_name"  =>  "PANCHHARI"],
            ["id" => 330, "district_id"  =>  "27", "thana_name"  =>  "RAMGARH"],
            ["id" => 331, "district_id"  =>  "28", "thana_name"  =>  "KHULNA"],
            ["id" => 332, "district_id"  =>  "28", "thana_name"  =>  "ARONGHATA"],
            ["id" => 333, "district_id"  =>  "28", "thana_name"  =>  "BATIAGHATA"],
            ["id" => 334, "district_id"  =>  "28", "thana_name"  =>  "DACOPE"],
            ["id" => 335, "district_id"  =>  "28", "thana_name"  =>  "DAULATPUR"],
            ["id" => 336, "district_id"  =>  "28", "thana_name"  =>  "DIGHOLIA"],
            ["id" => 337, "district_id"  =>  "28", "thana_name"  =>  "DUMURIA"],
            ["id" => 338, "district_id"  =>  "28", "thana_name"  =>  "HORINTANA"],
            ["id" => 339, "district_id"  =>  "28", "thana_name"  =>  "KHALISHPUR"],
            ["id" => 340, "district_id"  =>  "28", "thana_name"  =>  "KHAN JAHAN ALI"],
            ["id" => 341, "district_id"  =>  "28", "thana_name"  =>  "KHULNA SADAR"],
            ["id" => 342, "district_id"  =>  "28", "thana_name"  =>  "KOYRA"],
            ["id" => 343, "district_id"  =>  "28", "thana_name"  =>  "LABANCHORA"],
            ["id" => 344, "district_id"  =>  "28", "thana_name"  =>  "PAIKGACHA"],
            ["id" => 345, "district_id"  =>  "28", "thana_name"  =>  "PHULTALA"],
            ["id" => 346, "district_id"  =>  "28", "thana_name"  =>  "RUPSHA"],
            ["id" => 347, "district_id"  =>  "28", "thana_name"  =>  "SONADANGA MODEL"],
            ["id" => 348, "district_id"  =>  "28", "thana_name"  =>  "TEROKHADA"],
            ["id" => 349, "district_id"  =>  "29", "thana_name"  =>  "KISHOREGANJ"],
            ["id" => 350, "district_id"  =>  "29", "thana_name"  =>  "AUSTAGRAM"],
            ["id" => 351, "district_id"  =>  "29", "thana_name"  =>  "BAJITPUR"],
            ["id" => 352, "district_id"  =>  "29", "thana_name"  =>  "BHAIRAB"],
            ["id" => 353, "district_id"  =>  "29", "thana_name"  =>  "HOSSAINPUR"],
            ["id" => 354, "district_id"  =>  "29", "thana_name"  =>  "ITNA"],
            ["id" => 355, "district_id"  =>  "29", "thana_name"  =>  "KARIMGANJ"],
            ["id" => 356, "district_id"  =>  "29", "thana_name"  =>  "KATIADI"],
            ["id" => 357, "district_id"  =>  "29", "thana_name"  =>  "KISHOREGANJ SADAR"],
            ["id" => 358, "district_id"  =>  "29", "thana_name"  =>  "KULIARCHAR"],
            ["id" => 359, "district_id"  =>  "29", "thana_name"  =>  "MITHAMAIN"],
            ["id" => 360, "district_id"  =>  "29", "thana_name"  =>  "NIKLI"],
            ["id" => 361, "district_id"  =>  "29", "thana_name"  =>  "PAKUNDIA"],
            ["id" => 362, "district_id"  =>  "29", "thana_name"  =>  "TARAIL"],
            ["id" => 363, "district_id"  =>  "30", "thana_name"  =>  "KURIGRAM"],
            ["id" => 364, "district_id"  =>  "30", "thana_name"  =>  "BHURUNGAMARI"],
            ["id" => 365, "district_id"  =>  "30", "thana_name"  =>  "CHAR RAJIBPUR"],
            ["id" => 366, "district_id"  =>  "30", "thana_name"  =>  "CHILMARI"],
            ["id" => 367, "district_id"  =>  "30", "thana_name"  =>  "DUSMARA"],
            ["id" => 368, "district_id"  =>  "30", "thana_name"  =>  "KACHAKATA"],
            ["id" => 369, "district_id"  =>  "30", "thana_name"  =>  "KURIGRAM SADAR"],
            ["id" => 370, "district_id"  =>  "30", "thana_name"  =>  "NAGESHWARI"],
            ["id" => 371, "district_id"  =>  "30", "thana_name"  =>  "PHULBARI"],
            ["id" => 372, "district_id"  =>  "30", "thana_name"  =>  "RAJARHAT"],
            ["id" => 373, "district_id"  =>  "30", "thana_name"  =>  "ROWMARI"],
            ["id" => 374, "district_id"  =>  "30", "thana_name"  =>  "ULIPUR"],
            ["id" => 375, "district_id"  =>  "31", "thana_name"  =>  "KUSHTIA"],
            ["id" => 376, "district_id"  =>  "31", "thana_name"  =>  "BHERAMARA"],
            ["id" => 377, "district_id"  =>  "31", "thana_name"  =>  "DAULATPUR"],
            ["id" => 378, "district_id"  =>  "31", "thana_name"  =>  "ISLAMIC UNIVERSITY"],
            ["id" => 379, "district_id"  =>  "31", "thana_name"  =>  "KHOKSA"],
            ["id" => 380, "district_id"  =>  "31", "thana_name"  =>  "KUMARKHALI"],
            ["id" => 381, "district_id"  =>  "31", "thana_name"  =>  "KUSHTIA MODEL"],
            ["id" => 382, "district_id"  =>  "31", "thana_name"  =>  "MIRPUR"],
            ["id" => 383, "district_id"  =>  "32", "thana_name"  =>  "LAKSHMIPUR"],
            ["id" => 384, "district_id"  =>  "32", "thana_name"  =>  "CHANDRAGONJ"],
            ["id" => 385, "district_id"  =>  "32", "thana_name"  =>  "KAMALNAGAR"],
            ["id" => 386, "district_id"  =>  "32", "thana_name"  =>  "LAKSHMIPUR SADAR"],
            ["id" => 387, "district_id"  =>  "32", "thana_name"  =>  "RAIPUR"],
            ["id" => 388, "district_id"  =>  "32", "thana_name"  =>  "RAMGANJ"],
            ["id" => 389, "district_id"  =>  "32", "thana_name"  =>  "RAMGATI"],
            ["id" => 390, "district_id"  =>  "33", "thana_name"  =>  "LALMONIRHAT"],
            ["id" => 391, "district_id"  =>  "33", "thana_name"  =>  "ADITMARI"],
            ["id" => 392, "district_id"  =>  "33", "thana_name"  =>  "HATIBANDHA"],
            ["id" => 393, "district_id"  =>  "33", "thana_name"  =>  "KALIGANJ"],
            ["id" => 394, "district_id"  =>  "33", "thana_name"  =>  "LALMONIRHAT"],
            ["id" => 395, "district_id"  =>  "33", "thana_name"  =>  "PATGRAM"],
            ["id" => 396, "district_id"  =>  "34", "thana_name"  =>  "MADARIPUR"],
            ["id" => 397, "district_id"  =>  "34", "thana_name"  =>  "DASHAR"],
            ["id" => 398, "district_id"  =>  "34", "thana_name"  =>  "KALKINI"],
            ["id" => 399, "district_id"  =>  "34", "thana_name"  =>  "MADARIPUR SADAR"],
            ["id" => 400, "district_id"  =>  "34", "thana_name"  =>  "RAJOIR"],
            ["id" => 401, "district_id"  =>  "34", "thana_name"  =>  "SHIBCHAR"],
            ["id" => 402, "district_id"  =>  "35", "thana_name"  =>  "MAGURA"],
            ["id" => 403, "district_id"  =>  "35", "thana_name"  =>  "MAGURA SADAR"],
            ["id" => 404, "district_id"  =>  "35", "thana_name"  =>  "MOHAMMADPUR"],
            ["id" => 405, "district_id"  =>  "35", "thana_name"  =>  "SHALIKHA"],
            ["id" => 406, "district_id"  =>  "35", "thana_name"  =>  "SREEPUR"],
            ["id" => 407, "district_id"  =>  "36", "thana_name"  =>  "MANIKGANJ"],
            ["id" => 408, "district_id"  =>  "36", "thana_name"  =>  "DAULATPUR"],
            ["id" => 409, "district_id"  =>  "36", "thana_name"  =>  "GHIOR"],
            ["id" => 410, "district_id"  =>  "36", "thana_name"  =>  "HARIRAMPUR"],
            ["id" => 411, "district_id"  =>  "36", "thana_name"  =>  "MANIKGANJ SADAR"],
            ["id" => 412, "district_id"  =>  "36", "thana_name"  =>  "SATURIA"],
            ["id" => 413, "district_id"  =>  "36", "thana_name"  =>  "SHIBALAYA"],
            ["id" => 414, "district_id"  =>  "36", "thana_name"  =>  "SINGAIR"],
            ["id" => 415, "district_id"  =>  "37", "thana_name"  =>  "MEHERPUR"],
            ["id" => 416, "district_id"  =>  "37", "thana_name"  =>  "GANGNI"],
            ["id" => 417, "district_id"  =>  "37", "thana_name"  =>  "MEHERPUR SADAR"],
            ["id" => 418, "district_id"  =>  "37", "thana_name"  =>  "MUJIBNAGAR"],
            ["id" => 419, "district_id"  =>  "38", "thana_name"  =>  "MOULVIBAZAR"],
            ["id" => 420, "district_id"  =>  "38", "thana_name"  =>  "BARLEKHA"],
            ["id" => 421, "district_id"  =>  "38", "thana_name"  =>  "JURI"],
            ["id" => 422, "district_id"  =>  "38", "thana_name"  =>  "KOMOLGANJ"],
            ["id" => 423, "district_id"  =>  "38", "thana_name"  =>  "KULAURA"],
            ["id" => 424, "district_id"  =>  "38", "thana_name"  =>  "MOULVIBAZAR SADAR"],
            ["id" => 425, "district_id"  =>  "38", "thana_name"  =>  "RAJNAGAR"],
            ["id" => 426, "district_id"  =>  "38", "thana_name"  =>  "SRIMANGAL"],
            ["id" => 427, "district_id"  =>  "39", "thana_name"  =>  "MUNSHIGANJ"],
            ["id" => 428, "district_id"  =>  "39", "thana_name"  =>  "GAZARIA"],
            ["id" => 429, "district_id"  =>  "39", "thana_name"  =>  "LOUHAJONG"],
            ["id" => 430, "district_id"  =>  "39", "thana_name"  =>  "MUNSHIGANJ"],
            ["id" => 431, "district_id"  =>  "39", "thana_name"  =>  "PADMA SETU NORTH"],
            ["id" => 432, "district_id"  =>  "39", "thana_name"  =>  "SIRAJDIKHAN"],
            ["id" => 433, "district_id"  =>  "39", "thana_name"  =>  "SREENAGAR"],
            ["id" => 434, "district_id"  =>  "39", "thana_name"  =>  "TONGIBARI"],
            ["id" => 435, "district_id"  =>  "40", "thana_name"  =>  "MYMENSINGH"],
            ["id" => 436, "district_id"  =>  "40", "thana_name"  =>  "BHALUKA"],
            ["id" => 437, "district_id"  =>  "40", "thana_name"  =>  "DHOBAURA"],
            ["id" => 438, "district_id"  =>  "40", "thana_name"  =>  "FULBARIA"],
            ["id" => 439, "district_id"  =>  "40", "thana_name"  =>  "GAFORGAON"],
            ["id" => 440, "district_id"  =>  "40", "thana_name"  =>  "GOURIPUR"],
            ["id" => 441, "district_id"  =>  "40", "thana_name"  =>  "HALUAGHAT"],
            ["id" => 442, "district_id"  =>  "40", "thana_name"  =>  "ISHWARGANJ"],
            ["id" => 443, "district_id"  =>  "40", "thana_name"  =>  "KOTWALI"],
            ["id" => 444, "district_id"  =>  "40", "thana_name"  =>  "MUKTAGACHA"],
            ["id" => 445, "district_id"  =>  "40", "thana_name"  =>  "NANDAIL"],
            ["id" => 446, "district_id"  =>  "40", "thana_name"  =>  "PAGLA"],
            ["id" => 447, "district_id"  =>  "40", "thana_name"  =>  "PHULPUR"],
            ["id" => 448, "district_id"  =>  "40", "thana_name"  =>  "TARAKANDA"],
            ["id" => 449, "district_id"  =>  "40", "thana_name"  =>  "TRISHAL"],
            ["id" => 450, "district_id"  =>  "41", "thana_name"  =>  "NAOGAON"],
            ["id" => 451, "district_id"  =>  "41", "thana_name"  =>  "ATRAI"],
            ["id" => 452, "district_id"  =>  "41", "thana_name"  =>  "BADALGACHHI"],
            ["id" => 453, "district_id"  =>  "41", "thana_name"  =>  "DHAMOIRHAT"],
            ["id" => 454, "district_id"  =>  "41", "thana_name"  =>  "MAHADEBPUR"],
            ["id" => 455, "district_id"  =>  "41", "thana_name"  =>  "MANDA"],
            ["id" => 456, "district_id"  =>  "41", "thana_name"  =>  "NAOGAON SADAR"],
            ["id" => 457, "district_id"  =>  "41", "thana_name"  =>  "NIAMATPUR"],
            ["id" => 458, "district_id"  =>  "41", "thana_name"  =>  "PATNITALA"],
            ["id" => 459, "district_id"  =>  "41", "thana_name"  =>  "PORSHA"],
            ["id" => 460, "district_id"  =>  "41", "thana_name"  =>  "RANINAGAR"],
            ["id" => 461, "district_id"  =>  "41", "thana_name"  =>  "SAPAHAR"],
            ["id" => 462, "district_id"  =>  "42", "thana_name"  =>  "NARAIL"],
            ["id" => 463, "district_id"  =>  "42", "thana_name"  =>  "KALIA"],
            ["id" => 464, "district_id"  =>  "42", "thana_name"  =>  "LOHAGARA"],
            ["id" => 465, "district_id"  =>  "42", "thana_name"  =>  "NARAGATI"],
            ["id" => 466, "district_id"  =>  "42", "thana_name"  =>  "NARAIL SADAR"],
            ["id" => 467, "district_id"  =>  "43", "thana_name"  =>  "NARAYANGANJ"],
            ["id" => 468, "district_id"  =>  "43", "thana_name"  =>  "ARAIHAZAR"],
            ["id" => 469, "district_id"  =>  "43", "thana_name"  =>  "BANDAR"],
            ["id" => 470, "district_id"  =>  "43", "thana_name"  =>  "FATULLAH"],
            ["id" => 471, "district_id"  =>  "43", "thana_name"  =>  "NARAYANGANJ SADAR"],
            ["id" => 472, "district_id"  =>  "43", "thana_name"  =>  "RUPGANJ"],
            ["id" => 473, "district_id"  =>  "43", "thana_name"  =>  "SIDDHIRGANJ"],
            ["id" => 474, "district_id"  =>  "43", "thana_name"  =>  "SONARGAON"],
            ["id" => 475, "district_id"  =>  "44", "thana_name"  =>  "NARSINGDI"],
            ["id" => 476, "district_id"  =>  "44", "thana_name"  =>  "BELABO"],
            ["id" => 477, "district_id"  =>  "44", "thana_name"  =>  "MADHABDI"],
            ["id" => 478, "district_id"  =>  "44", "thana_name"  =>  "MONOHARDI"],
            ["id" => 479, "district_id"  =>  "44", "thana_name"  =>  "NARSINGDI SADAR"],
            ["id" => 480, "district_id"  =>  "44", "thana_name"  =>  "PALASH"],
            ["id" => 481, "district_id"  =>  "44", "thana_name"  =>  "RAIPURA"],
            ["id" => 482, "district_id"  =>  "44", "thana_name"  =>  "SHIBPUR"],
            ["id" => 483, "district_id"  =>  "45", "thana_name"  =>  "NATORE"],
            ["id" => 484, "district_id"  =>  "45", "thana_name"  =>  "BAGATIPARA"],
            ["id" => 485, "district_id"  =>  "45", "thana_name"  =>  "BARAIGRAM"],
            ["id" => 486, "district_id"  =>  "45", "thana_name"  =>  "GURUDASPUR"],
            ["id" => 487, "district_id"  =>  "45", "thana_name"  =>  "LALPUR"],
            ["id" => 488, "district_id"  =>  "45", "thana_name"  =>  "NALDANGA"],
            ["id" => 489, "district_id"  =>  "45", "thana_name"  =>  "NATORE"],
            ["id" => 490, "district_id"  =>  "45", "thana_name"  =>  "SINGRA"],
            ["id" => 491, "district_id"  =>  "46", "thana_name"  =>  "NETROKONA"],
            ["id" => 492, "district_id"  =>  "46", "thana_name"  =>  "ATPARA"],
            ["id" => 493, "district_id"  =>  "46", "thana_name"  =>  "BARHATTA"],
            ["id" => 494, "district_id"  =>  "46", "thana_name"  =>  "DURGAPUR"],
            ["id" => 495, "district_id"  =>  "46", "thana_name"  =>  "KALMAKANDA"],
            ["id" => 496, "district_id"  =>  "46", "thana_name"  =>  "KENDUA"],
            ["id" => 497, "district_id"  =>  "46", "thana_name"  =>  "KHALIAJURI"],
            ["id" => 498, "district_id"  =>  "46", "thana_name"  =>  "MODON"],
            ["id" => 499, "district_id"  =>  "46", "thana_name"  =>  "MOHANGANJ"],
            ["id" => 500, "district_id"  =>  "46", "thana_name"  =>  "NETROKONA SADAR "],
            ["id" => 501, "district_id"  =>  "46", "thana_name"  =>  "PURBODHALA"],
            ["id" => 502, "district_id"  =>  "47", "thana_name"  =>  "NILPHAMARI"],
            ["id" => 503, "district_id"  =>  "47", "thana_name"  =>  "DIMLA"],
            ["id" => 504, "district_id"  =>  "47", "thana_name"  =>  "DOMAR"],
            ["id" => 505, "district_id"  =>  "47", "thana_name"  =>  "JALDHAKA"],
            ["id" => 506, "district_id"  =>  "47", "thana_name"  =>  "KISHOREGANJ"],
            ["id" => 507, "district_id"  =>  "47", "thana_name"  =>  "NILPHAMARI SADAR"],
            ["id" => 508, "district_id"  =>  "47", "thana_name"  =>  "SAIDPUR"],
            ["id" => 509, "district_id"  =>  "48", "thana_name"  =>  "NOAKHALI"],
            ["id" => 510, "district_id"  =>  "48", "thana_name"  =>  "BEGUMGANJ"],
            ["id" => 511, "district_id"  =>  "48", "thana_name"  =>  "BHASAN CHAR"],
            ["id" => 512, "district_id"  =>  "48", "thana_name"  =>  "CHARJABBAR"],
            ["id" => 513, "district_id"  =>  "48", "thana_name"  =>  "CHATKHIL"],
            ["id" => 514, "district_id"  =>  "48", "thana_name"  =>  "COMPANIGONJ"],
            ["id" => 515, "district_id"  =>  "48", "thana_name"  =>  "HATIYA"],
            ["id" => 516, "district_id"  =>  "48", "thana_name"  =>  "KABIRHAT"],
            ["id" => 517, "district_id"  =>  "48", "thana_name"  =>  "SENBAGH"],
            ["id" => 518, "district_id"  =>  "48", "thana_name"  =>  "SONAIMURI"],
            ["id" => 519, "district_id"  =>  "48", "thana_name"  =>  "SUDHARAM"],
            ["id" => 520, "district_id"  =>  "49", "thana_name"  =>  "PABNA"],
            ["id" => 521, "district_id"  =>  "49", "thana_name"  =>  "AMINPUR"],
            ["id" => 522, "district_id"  =>  "49", "thana_name"  =>  "ATAIKULA"],
            ["id" => 523, "district_id"  =>  "49", "thana_name"  =>  "ATGHARIA"],
            ["id" => 524, "district_id"  =>  "49", "thana_name"  =>  "BERA"],
            ["id" => 525, "district_id"  =>  "49", "thana_name"  =>  "BHANGURA"],
            ["id" => 526, "district_id"  =>  "49", "thana_name"  =>  "CHATMOHAR"],
            ["id" => 527, "district_id"  =>  "49", "thana_name"  =>  "FARIDPUR"],
            ["id" => 528, "district_id"  =>  "49", "thana_name"  =>  "ISHWARDI"],
            ["id" => 529, "district_id"  =>  "49", "thana_name"  =>  "PABNA SADAR"],
            ["id" => 530, "district_id"  =>  "49", "thana_name"  =>  "SANTHIA"],
            ["id" => 531, "district_id"  =>  "49", "thana_name"  =>  "SUJANAGAR"],
            ["id" => 532, "district_id"  =>  "50", "thana_name"  =>  "PANCHAGARH"],
            ["id" => 533, "district_id"  =>  "50", "thana_name"  =>  "ATWARI"],
            ["id" => 534, "district_id"  =>  "50", "thana_name"  =>  "BODA"],
            ["id" => 535, "district_id"  =>  "50", "thana_name"  =>  "DEBIGANJ"],
            ["id" => 536, "district_id"  =>  "50", "thana_name"  =>  "PANCHAGARH SADAR"],
            ["id" => 537, "district_id"  =>  "50", "thana_name"  =>  "TETULIA"],
            ["id" => 538, "district_id"  =>  "51", "thana_name"  =>  "PATUAKHALI"],
            ["id" => 539, "district_id"  =>  "51", "thana_name"  =>  "BAUPHAL"],
            ["id" => 540, "district_id"  =>  "51", "thana_name"  =>  "DASHMINA"],
            ["id" => 541, "district_id"  =>  "51", "thana_name"  =>  "DUMKI"],
            ["id" => 542, "district_id"  =>  "51", "thana_name"  =>  "GALACHIPA"],
            ["id" => 543, "district_id"  =>  "51", "thana_name"  =>  "KALAPARA"],
            ["id" => 544, "district_id"  =>  "51", "thana_name"  =>  "MIRZAGANJ"],
            ["id" => 545, "district_id"  =>  "51", "thana_name"  =>  "MOHIPUR"],
            ["id" => 546, "district_id"  =>  "51", "thana_name"  =>  "PATUAKHALI SADAR"],
            ["id" => 547, "district_id"  =>  "51", "thana_name"  =>  "RANGABALI"],
            ["id" => 548, "district_id"  =>  "52", "thana_name"  =>  "PIROJPUR"],
            ["id" => 549, "district_id"  =>  "52", "thana_name"  =>  "BHANDARIA"],
            ["id" => 550, "district_id"  =>  "52", "thana_name"  =>  "INDURKANI"],
            ["id" => 551, "district_id"  =>  "52", "thana_name"  =>  "KAWKHALI"],
            ["id" => 552, "district_id"  =>  "52", "thana_name"  =>  "MATHBARIA"],
            ["id" => 553, "district_id"  =>  "52", "thana_name"  =>  "NAZIRPUR"],
            ["id" => 554, "district_id"  =>  "52", "thana_name"  =>  "NESARABAD"],
            ["id" => 555, "district_id"  =>  "52", "thana_name"  =>  "PIROJPUR SADAR"],
            ["id" => 556, "district_id"  =>  "53", "thana_name"  =>  "RAJBARI"],
            ["id" => 557, "district_id"  =>  "53", "thana_name"  =>  "BALIAKANDI"],
            ["id" => 558, "district_id"  =>  "53", "thana_name"  =>  "GOALANDA GHAT"],
            ["id" => 559, "district_id"  =>  "53", "thana_name"  =>  "KALUKHALI"],
            ["id" => 560, "district_id"  =>  "53", "thana_name"  =>  "PANGSHA"],
            ["id" => 561, "district_id"  =>  "53", "thana_name"  =>  "RAJBARI"],
            ["id" => 562, "district_id"  =>  "54", "thana_name"  =>  "RAJSHAHI"],
            ["id" => 563, "district_id"  =>  "54", "thana_name"  =>  "AIRPORT"],
            ["id" => 564, "district_id"  =>  "54", "thana_name"  =>  "BAGHA"],
            ["id" => 565, "district_id"  =>  "54", "thana_name"  =>  "BAGMARA"],
            ["id" => 566, "district_id"  =>  "54", "thana_name"  =>  "BILPUKUR"],
            ["id" => 567, "district_id"  =>  "54", "thana_name"  =>  "BOALIA MODEL"],
            ["id" => 568, "district_id"  =>  "54", "thana_name"  =>  "CHANDRIMA"],
            ["id" => 569, "district_id"  =>  "54", "thana_name"  =>  "CHARGHAT"],
            ["id" => 570, "district_id"  =>  "54", "thana_name"  =>  "DAMKURA"],
            ["id" => 571, "district_id"  =>  "54", "thana_name"  =>  "DURGAPUR"],
            ["id" => 572, "district_id"  =>  "54", "thana_name"  =>  "GODAGARI"],
            ["id" => 573, "district_id"  =>  "54", "thana_name"  =>  "KASHIADANGA"],
            ["id" => 574, "district_id"  =>  "54", "thana_name"  =>  "KATAKHALI"],
            ["id" => 575, "district_id"  =>  "54", "thana_name"  =>  "KORNAHAR"],
            ["id" => 576, "district_id"  =>  "54", "thana_name"  =>  "MOHANPUR"],
            ["id" => 577, "district_id"  =>  "54", "thana_name"  =>  "MOTIHAR"],
            ["id" => 578, "district_id"  =>  "54", "thana_name"  =>  "PABA"],
            ["id" => 579, "district_id"  =>  "54", "thana_name"  =>  "PUTHIA"],
            ["id" => 580, "district_id"  =>  "54", "thana_name"  =>  "RAJPARA"],
            ["id" => 581, "district_id"  =>  "54", "thana_name"  =>  "SHAH MAKHDUM"],
            ["id" => 582, "district_id"  =>  "54", "thana_name"  =>  "TANOR"],
            ["id" => 583, "district_id"  =>  "55", "thana_name"  =>  "RANGAMATI"],
            ["id" => 584, "district_id"  =>  "55", "thana_name"  =>  "BAGHAICHHARI"],
            ["id" => 585, "district_id"  =>  "55", "thana_name"  =>  "BARKAL"],
            ["id" => 586, "district_id"  =>  "55", "thana_name"  =>  "BELAICHHARI"],
            ["id" => 587, "district_id"  =>  "55", "thana_name"  =>  "CHANDROGHONA"],
            ["id" => 588, "district_id"  =>  "55", "thana_name"  =>  "JURAICHHARI"],
            ["id" => 589, "district_id"  =>  "55", "thana_name"  =>  "KAPTAI"],
            ["id" => 590, "district_id"  =>  "55", "thana_name"  =>  "KAWKHALI"],
            ["id" => 591, "district_id"  =>  "55", "thana_name"  =>  "KOTWALI"],
            ["id" => 592, "district_id"  =>  "55", "thana_name"  =>  "LANGADU"],
            ["id" => 593, "district_id"  =>  "55", "thana_name"  =>  "NANIARCHAR"],
            ["id" => 594, "district_id"  =>  "55", "thana_name"  =>  "RAJASTHALI"],
            ["id" => 595, "district_id"  =>  "55", "thana_name"  =>  "SAJEK"],
            ["id" => 596, "district_id"  =>  "56", "thana_name"  =>  "RANGPUR"],
            ["id" => 597, "district_id"  =>  "56", "thana_name"  =>  "BADARGANJ"],
            ["id" => 598, "district_id"  =>  "56", "thana_name"  =>  "GANGACHARA"],
            ["id" => 599, "district_id"  =>  "56", "thana_name"  =>  "HARAGACH"],
            ["id" => 600, "district_id"  =>  "56", "thana_name"  =>  "HAZIRHAT"],
            ["id" => 601, "district_id"  =>  "56", "thana_name"  =>  "KAUNIA"],
            ["id" => 602, "district_id"  =>  "56", "thana_name"  =>  "KOTWALI METRO"],
            ["id" => 603, "district_id"  =>  "56", "thana_name"  =>  "MAHIGONJ"],
            ["id" => 604, "district_id"  =>  "56", "thana_name"  =>  "MITHA PUKUR"],
            ["id" => 605, "district_id"  =>  "56", "thana_name"  =>  "PIRGACHHA"],
            ["id" => 606, "district_id"  =>  "56", "thana_name"  =>  "PIRGANJ"],
            ["id" => 607, "district_id"  =>  "56", "thana_name"  =>  "PORSHURAM"],
            ["id" => 608, "district_id"  =>  "56", "thana_name"  =>  "RANGPUR SADAR"],
            ["id" => 609, "district_id"  =>  "56", "thana_name"  =>  "TAJHAT"],
            ["id" => 610, "district_id"  =>  "56", "thana_name"  =>  "TARAGANJ"],
            ["id" => 611, "district_id"  =>  "57", "thana_name"  =>  "SATKHIRA"],
            ["id" => 612, "district_id"  =>  "57", "thana_name"  =>  "ASHASHUNI"],
            ["id" => 613, "district_id"  =>  "57", "thana_name"  =>  "DEBHATA"],
            ["id" => 614, "district_id"  =>  "57", "thana_name"  =>  "KALAROA"],
            ["id" => 615, "district_id"  =>  "57", "thana_name"  =>  "KALIGANJ"],
            ["id" => 616, "district_id"  =>  "57", "thana_name"  =>  "PATKELGHATA"],
            ["id" => 617, "district_id"  =>  "57", "thana_name"  =>  "SATKHIRA SADAR"],
            ["id" => 618, "district_id"  =>  "57", "thana_name"  =>  "SHYAMNAGAR"],
            ["id" => 619, "district_id"  =>  "57", "thana_name"  =>  "TALA"],
            ["id" => 620, "district_id"  =>  "58", "thana_name"  =>  "SHARIATPUR"],
            ["id" => 621, "district_id"  =>  "58", "thana_name"  =>  "BHEDARGANJ"],
            ["id" => 622, "district_id"  =>  "58", "thana_name"  =>  "DAMUDYA"],
            ["id" => 623, "district_id"  =>  "58", "thana_name"  =>  "GOSAIRHAT"],
            ["id" => 624, "district_id"  =>  "58", "thana_name"  =>  "JAJIRA"],
            ["id" => 625, "district_id"  =>  "58", "thana_name"  =>  "NARIA"],
            ["id" => 626, "district_id"  =>  "58", "thana_name"  =>  "PADMA SETU SOUTH"],
            ["id" => 627, "district_id"  =>  "58", "thana_name"  =>  "PALONG MODEL"],
            ["id" => 628, "district_id"  =>  "58", "thana_name"  =>  "SHAKHIPUR"],
            ["id" => 629, "district_id"  =>  "59", "thana_name"  =>  "SHERPUR"],
            ["id" => 630, "district_id"  =>  "59", "thana_name"  =>  "JHINAIGATI"],
            ["id" => 631, "district_id"  =>  "59", "thana_name"  =>  "NAKLA"],
            ["id" => 632, "district_id"  =>  "59", "thana_name"  =>  "NALITABARI"],
            ["id" => 633, "district_id"  =>  "59", "thana_name"  =>  "SHERPUR"],
            ["id" => 634, "district_id"  =>  "59", "thana_name"  =>  "SRIBARDI"],
            ["id" => 635, "district_id"  =>  "60", "thana_name"  =>  "SIRAJGANJ"],
            ["id" => 636, "district_id"  =>  "60", "thana_name"  =>  "BANGABANDHU SETU WEST"],
            ["id" => 637, "district_id"  =>  "60", "thana_name"  =>  "BELKUCHI"],
            ["id" => 638, "district_id"  =>  "60", "thana_name"  =>  "CHOWHALI"],
            ["id" => 639, "district_id"  =>  "60", "thana_name"  =>  "ENAYETPUR"],
            ["id" => 640, "district_id"  =>  "60", "thana_name"  =>  "KAMARKHANDA"],
            ["id" => 641, "district_id"  =>  "60", "thana_name"  =>  "KAZIPUR"],
            ["id" => 642, "district_id"  =>  "60", "thana_name"  =>  "RAIGONJ"],
            ["id" => 643, "district_id"  =>  "60", "thana_name"  =>  "SALANGA"],
            ["id" => 644, "district_id"  =>  "60", "thana_name"  =>  "SHAHZADPUR"],
            ["id" => 645, "district_id"  =>  "60", "thana_name"  =>  "SIRAJGANJ"],
            ["id" => 646, "district_id"  =>  "60", "thana_name"  =>  "TARASH"],
            ["id" => 647, "district_id"  =>  "60", "thana_name"  =>  "ULLAPARA MODEL"],
            ["id" => 648, "district_id"  =>  "61", "thana_name"  =>  "SUNAMGANJ"],
            ["id" => 649, "district_id"  =>  "61", "thana_name"  =>  "BISHWAMBARPUR"],
            ["id" => 650, "district_id"  =>  "61", "thana_name"  =>  "CHHATAK"],
            ["id" => 651, "district_id"  =>  "61", "thana_name"  =>  "DAKSHIN SUNAMGANJ"],
            ["id" => 652, "district_id"  =>  "61", "thana_name"  =>  "DERAI"],
            ["id" => 653, "district_id"  =>  "61", "thana_name"  =>  "DHARAMPASHA"],
            ["id" => 654, "district_id"  =>  "61", "thana_name"  =>  "DOWARABAZAR"],
            ["id" => 655, "district_id"  =>  "61", "thana_name"  =>  "JAGANNATHPUR"],
            ["id" => 656, "district_id"  =>  "61", "thana_name"  =>  "JAMALGANJ"],
            ["id" => 657, "district_id"  =>  "61", "thana_name"  =>  "MADHANAGAR"],
            ["id" => 658, "district_id"  =>  "61", "thana_name"  =>  "SULLAH"],
            ["id" => 659, "district_id"  =>  "61", "thana_name"  =>  "SUNAMGANJ SADAR"],
            ["id" => 660, "district_id"  =>  "61", "thana_name"  =>  "TAHIRPUR"],
            ["id" => 661, "district_id"  =>  "62", "thana_name"  =>  "SYLHET"],
            ["id" => 662, "district_id"  =>  "62", "thana_name"  =>  "AIRPORT"],
            ["id" => 663, "district_id"  =>  "62", "thana_name"  =>  "BALAGANJ"],
            ["id" => 664, "district_id"  =>  "62", "thana_name"  =>  "BEANIBAZAR"],
            ["id" => 665, "district_id"  =>  "62", "thana_name"  =>  "BISHWANATH"],
            ["id" => 666, "district_id"  =>  "62", "thana_name"  =>  "COMPANYGONJ"],
            ["id" => 667, "district_id"  =>  "62", "thana_name"  =>  "FENCHUGONJ"],
            ["id" => 668, "district_id"  =>  "62", "thana_name"  =>  "GOLAPGONJ"],
            ["id" => 669, "district_id"  =>  "62", "thana_name"  =>  "GOWAINGHAT"],
            ["id" => 670, "district_id"  =>  "62", "thana_name"  =>  "JAINTAPUR"],
            ["id" => 671, "district_id"  =>  "62", "thana_name"  =>  "JALALABAD"],
            ["id" => 672, "district_id"  =>  "62", "thana_name"  =>  "KANAIGHAT"],
            ["id" => 673, "district_id"  =>  "62", "thana_name"  =>  "KOTWALI"],
            ["id" => 674, "district_id"  =>  "62", "thana_name"  =>  "MOGLABAZAR"],
            ["id" => 675, "district_id"  =>  "62", "thana_name"  =>  "OSMANINAGAR"],
            ["id" => 676, "district_id"  =>  "62", "thana_name"  =>  "SHAHPORAN"],
            ["id" => 677, "district_id"  =>  "62", "thana_name"  =>  "SOUTH SURMA"],
            ["id" => 678, "district_id"  =>  "62", "thana_name"  =>  "ZOKIGANJ"],
            ["id" => 679, "district_id"  =>  "63", "thana_name"  =>  "TANGAIL"],
            ["id" => 680, "district_id"  =>  "63", "thana_name"  =>  "BANGABANDHU SETU EAST"],
            ["id" => 681, "district_id"  =>  "63", "thana_name"  =>  "BASAIL"],
            ["id" => 682, "district_id"  =>  "63", "thana_name"  =>  "BHUAPUR"],
            ["id" => 683, "district_id"  =>  "63", "thana_name"  =>  "DELDUAR"],
            ["id" => 684, "district_id"  =>  "63", "thana_name"  =>  "DHANBARI"],
            ["id" => 685, "district_id"  =>  "63", "thana_name"  =>  "GHATAIL"],
            ["id" => 686, "district_id"  =>  "63", "thana_name"  =>  "GOPALPUR"],
            ["id" => 687, "district_id"  =>  "63", "thana_name"  =>  "KALIHATI"],
            ["id" => 688, "district_id"  =>  "63", "thana_name"  =>  "MADHUPUR"],
            ["id" => 689, "district_id"  =>  "63", "thana_name"  =>  "MIRZAPUR"],
            ["id" => 690, "district_id"  =>  "63", "thana_name"  =>  "NAGARPUR"],
            ["id" => 691, "district_id"  =>  "63", "thana_name"  =>  "SAKHIPUR"],
            ["id" => 692, "district_id"  =>  "63", "thana_name"  =>  "TANGAIL SADAR"],
            ["id" => 693, "district_id"  =>  "64", "thana_name"  =>  "THAKURGAON"],
            ["id" => 694, "district_id"  =>  "64", "thana_name"  =>  "BALIADANGI"],
            ["id" => 695, "district_id"  =>  "64", "thana_name"  =>  "HARIPUR"],
            ["id" => 696, "district_id"  =>  "64", "thana_name"  =>  "PIRGANJ"],
            ["id" => 697, "district_id"  =>  "64", "thana_name"  =>  "RANISANKAIL"],
            ["id" => 698, "district_id"  =>  "64", "thana_name"  =>  "RUHIA"],
            ["id" => 699, "district_id"  =>  "64", "thana_name"  =>  "THAKURGAON SADAR"],
        ]);
    }
}
